### ISSUE TITLE
Test de verificare cunostinte RolePlay

### ISSUE THREAD

**Issue by DevotomSolution** [DevotomSolution/Atlas-RolePlay-Server#5]
La inregistrarea pe server acesta va genera un test pe care trebuie is completezi si sa il treci pentru a fi declarat apt de a lua parte la jocurile de rol pe server, astfel incat sa iti stabileasca nivelul de RolePlay pe care il detine respectivul jucator.

@M3trix71 @Muscui90090 se vor ocupa de intrebari

**Comment by M3trix71** [comment]
**ATLAS RP TEST INTRARE INTREBARI**
1-Ce se intelege prin termenul **ROLEPLAY**
2-Ce se intelege prin termenul **METAGAMING**
3-Ce se intelege prin termenul **MIXING**
4-Ce se intelege prin termenul **POWERGAMING**
5-Ce se intelege prin termenul **NOFEAR**
6-Ce se intelege prin termenul **PROVOKING**
7-Ce se intelege prin termenul **COPBAIT**
8-Ce se intelege prin termenul **BOMBARDIER**
9-Ce trebuie sa faci prima daca cand intri pe server
10-Cu ce viteza ai voie sa circuli in oras
11-Cu ce viteza ai voie sa circuli pe teren de tip OFF-ROAD cu o masina cu garda joasa
12-Ce se intelege prin termenul **DEATHMATCH**
13-Ce se intelege prin termenul **CHIKEN-RUN**
14-Ce se intelege prin termenul **PLAYER-KILL**
15-Ce se intelege prin termenul **CHARACTER-KILL**
16-Care este viteza maxima admisa pe autostrada
17-Ce se intelege prin termenul **ROB&KILL**
18-In care dintre urmatoarele cazuri se considera **INSELATORIE/SCAM**
19-Tu sau unul dintre prietenii cu care te joci, gasiti un BUG prin care puteti obtine un avantaj fata de ceilalti playeri, ce trebuie sa faci?
20-Ce nu ai voie sa faci cu masina pe care o primesti de la JOBUL LEGAL
21-Care sunt bunurile pe care un player le poate cere in schimbul unui ostatic?
22-In care dintre situatiile de mai jos este permisa actiuni de tip TERORISM
23-In care dintre conditiile de mai jos este permisa efectuarea unei manevre de tip PIT-STOP
24-Ce trebuie sa aveti in vedere atungi cand vreti sa JEFUITI
25-Un prieten cu care te joci pe acest server iti scrie pe discord sa va intalniti in fata la banca Fleeca de langa SHOWROOM pentru a-ti oferi niste bani, 
ce consideri ca este corect sa faci?
26-Intre ce interval orar ai voie sa jefuiesti persoane aflate in zone rau famate?
27-Dupa cat timp ai dreptul de a jefui din nou aceiasi persoana pe care ai mai jefuit-o si inainte?
28-In ce situatii aveti voie sa atacati un transport de detinuti?
29-Unde este permisa aterizarea cu elicopterele?
30-De cate persoane este nevoie atunci cand rapiti un jucator si doriti sa il transportati cu masina?

**Comment by M3trix71** [comment]
**ATLAS RP TEST INTRARE INTREBARI+RASPUNSURI**
1-Cu ce viteza ai voie sa circuli pe teren de tip OFF-ROAD cu o masina cu garda joasa?
 -Viteza cuprinsa intre 50-60 km/h si in cazul unei urmariri sau situatii tensionate 60-80 km/h
 -Viteza cuprisa intre 60-80 km/h si in cazul unei urmariri sau situatii tensionate 80-100 km/h
 -Viteza cuprinsa intre 20-30 km/h si in cazul unei urmariri sau situatii tensionate 30-50 km/h
 -Viteza cuprinsa intre 30-50 km/h si in cazul unei urmariri sau situatii tensionate 50-70 km/h-----raspuns corect
 ----------------------------------------------------------------------------------------------------------------------------
 2-In care dintre conditiile de mai jos este permisa efectuarea unei manevre de tip PIT-STOP?
 -Oricand si orunde atata timp cat exista permisiunea unui Inspector+ si cu orice tip de masina
 -Doar in afara orasului cu aprobarea unui Inspector+ si cu orice masina
 -In oras atunci cand suspectul circula cu o viteza maxima de 100 km/h si inafara orasului cu 150 km/h si cu orice tip de masina.
 -In oras atunci cand suspectul circula cu o viteza maxima de 100 km/h si inafara orasului cu 150 km/h, cu orice masina cu garda inalta.---raspund corect
--------------------------------------------------------------------------------------------------------------------------------------------
3-Intre ce interval orar ai voie sa jefuiesti persoane aflate in zone rau famate?
 -Oricand vrea muschiul tau
 -De dimineata pana seara atata timp cat ai grija sa nu te prinda politia
 -De la ora 19:00-00:00
 -Intre orele 20:00-08:00---raspuns corect
--------------------------------------------------------------------------------------------------------------------------------------------
 4-Care sunt bunurile pe care un player le poate cere in schimbul unui ostatic?
 -Orice si oricat vrei tu pentru ca este ostatic si viata lui conteaza
 -Bani si bunuri in valoare de 500.000 dolari+orice vehicul din Departamentul de Politie
 -Bani si bunuri in valoare de 500.000 dolari+orice vehicul din Departamentul de Politie cu exceptia vehiculelor din departementul SIAS
 -Bani si bunuri in valoare de 200.000 dolari sau alegerea unui vehicul din Departamentul de Politie cu exceptie vehiculelor din departamentul SIAS---raspuns corect
--------------------------------------------------------------------------------------------------------------------------------------------
5-Ce trebuie sa ai in vedere atunci cand esti la JOBUL LEGAL
 -Ca poti folosi masina in orice scopuri inclusiv cele personale sau participarea la actiuni ilegale
 -Ca te poti duce in zonele rau famate si sa incepi sa injuri si sa faci misto de toata lumea pentru ca tu esti la job legal si nu au voie sa iti faca nimic.
 -Ca poti sa te folosti de masina de la **JOB LEGAL** pentru a depozita lucruri ilegale
 -Ca trebuie sa iti mentii un comportament adevat pe tot timpul turei de munca, ca masina poate fi folosita doar in scopul jobului, si ca nu ai voie sa savarseti nici un act ilegal pe timpul programului de lucru-----raspuns corect
--------------------------------------------------------------------------------------------------------------------------------------------
6-Ce trebuie sa faci prima daca cand intri pe server
 -Sa te duci si sa incepi sa faci job pentru ca vrei bani si avere cat ma rapid
 -Sa te duci si sa te imbraci ca si politist pentru ca asta este ceea ce vrei sa faci tu
 -Sa iti faci un buletin, sa te schimbi si mai apoi sa obtii un permis de conducere----raspuns corect
 -Sa te duci si sa ti schimbi imbracamintea ca mai apoi sa faci orice vrea muschiul tau 
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by DevotomSolution** [comment]
Intrebari implementate.
System momentan dezactivat pana la iesirea din teste
